### ISSUE TITLE
sbt 'Duplicate mappings' error

### ISSUE THREAD

**Issue by francisdb** [choucrifahed/sbt-elm#3]
run `sbt clean test`

```
[info] Exporting web-assets:module2
[info] Exporting web-assets-test:module2
[info] Exporting web-assets:rootmodule
...
[error] (root/web-assets-test:assets) Duplicate mappings:
[error]     /project/target/web/public/test/public/elmMain.js
[error] from
[error]     /project/target/web/elm/test/js/elmMain.js
[error]         /project/target/web/web-modules/test/webjars/lib/rootmodule/elmMain.js
```

found some related issue:
https://github.com/sbt/sbt/issues/2047

**Comment by francisdb** [comment]
@choucrifahed can you reproduce this one? Could again be related to my multimodule project.

**Comment by francisdb** [comment]
Not related to multimodule project, also seeing this when running `sbt test` on the play example project

**Comment by francisdb** [comment]
Looks like this bug was inherited from sbt-purescript
https://github.com/eamelink/sbt-purescript/issues/14

And there is a very small patch needed to fix this
https://github.com/eamelink/sbt-purescript/pull/15/files

@choucrifahed any chance you could apply this patch here?

**Comment by choucrifahed** [comment]
@francisdb thanks a lot for your investigation and the issues you opened! I tested your fix but it doesn't work :-( not sure it's a change in the right direction

**Comment by francisdb** [comment]
:-( will have to look further

maybe checking one of the official SbtWeb plugins will help (even if they also are 2y old)
https://github.com/sbt/sbt-uglify
https://github.com/sbt/sbt-coffeescript
